# Copyright (c) 2024 Graphcore Ltd. All rights reserved.
# Modified from minimal-mistakes/_config.yml

# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Graphcore Research Blog
name: Graphcore Ltd
locale: "en-GB"
email: research@graphcore.ai
baseurl: "/"
description: >- # this means to ignore newlines until "baseurl:"
  The official Graphcore Research blog.
twitter:
  username: "GCResearchTeam"
og_image: "/assets/images/gc-symbol-pink-padded.png"
github_username: graphcore-research
repository: graphcore-research/graphcore-research.github.io
minimal_mistakes_skin: default
# search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Graphcore Research"
  avatar : "/assets/images/gc-symbol-pink.png"
  bio    : "Our mission is to follow and contribute to the advancement of AI research, aiming to characterise the computational requirements of machine intelligence."
  links:
    - label: "Graphcore"
      icon: "fas fa-fw fa-microchip"
      url: "https://www.graphcore.ai/"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/GCResearchTeam"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/graphcore-research"
    - label: "Subscribe"
      icon: "fas fa-fw fa-envelope"
      url: "https://www.graphcore.ai/graphcore-research-newsletter-1"
    - label: "Our Papers"
      icon: "fas fa-fw fa-book"
      url: "/publications"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/GCResearchTeam"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/graphcore-research"
    - label: "Subscribe"
      icon: "fas fa-fw fa-envelope"
      url: "https://www.graphcore.ai/graphcore-research-newsletter-1"
    - label: "Our Papers"
      icon: "fas fa-fw fa-book"
      url: "/publications"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      words_per_minute: 160
      comments: true
      share: true
      related: true
      usemathjax: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

google_analytics: "G-QCZ6T9KWHQ"

comments:
  provider: "giscus"
  giscus:
    repo_id              : "R_kgDOLFiloQ"  # Shown during giscus setup at https://giscus.app
    category_name        : "Blog"  # Full text name of the category
    category_id          : "DIC_kwDOLFiloc4CchQw"  # Shown during giscus setup at https://giscus.app
    discussion_term      : "pathname"  # "pathname" (default), "url", "title", "og:title"
    reactions_enabled    : 1  # '1' for enabled (default), '0' for disabled
    theme                : "light"  # "light" (default), "dark", "dark_dimmed", "transparent_dark", "preferred_color_scheme"
