# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Graphcore Research Blog
name: Graphcore Ltd
locale: "en-GB"
email: research@graphcore.ai
baseurl: "/"
description: >- # this means to ignore newlines until "baseurl:"
  The official Graphcore Research blog.
# twitter_username: username
github_username: graphcore-research
repository: graphcore-research/graphcore-research.github.io
minimal_mistakes_skin: default
# search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Graphcore Research"
  avatar : "/assets/images/gc-symbol-pink.png"
  bio    : "Our research team’s mission is to follow and contribute to the advancement of AI research, aiming to characterize the computational requirements of Machine Intelligence."
  links:
    - label: "Graphcore"
      icon: "fas fa-fw fa-microchip"
      url: "https://www.graphcore.ai/"
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/graphcore-research"
    - label: "Our Papers"
      icon: "fas fa-fw fa-book"
      url: "https://www.graphcore.ai/resources/research-papers"

footer:
  links:
    # - label: "Twitter"
    #   icon: "fab fa-fw fa-twitter-square"
    #   url: "https://twitter.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/graphcore-research"
    - label: "Our Papers"
      icon: "fas fa-fw fa-book"
      url: "https://www.graphcore.ai/resources/research-papers"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      words_per_minute: 150
      comments: true
      share: true
      related: true
      usemathjax: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-QCZ6T9KWHQ"
    anonymize_ip: false # default
