authors:

  albertoc:
    name: Alberto Cattaneo
    description: Research Scientist
    avatar: img/authors/_default.jpg

  alexc:
    name: Alex Cunha
    description: ML Engineer
    avatar: img/authors/_default.jpg

  alexp:
    name: Alexandre Payot
    description: ML Engineer
    avatar: img/authors/_default.jpg

  ariannas:
    name: Arianna Saracino
    description: ML Engineering Manager
    avatar: img/authors/_default.jpg

  benoitg:
    name: Benoit Gaujac
    description: Research Scientist
    avatar: img/authors/_default.jpg

  callumm:
    name: Callum McLean
    description: Research Scientist
    avatar: img/authors/_default.jpg

  carlo:
    name: Carlo Luschi
    description: VP & Head of Research
    avatar: img/authors/_default.jpg

  charlieb:
    name: Charlie Blake
    description: Research Engineer
    avatar: img/authors/_default.jpg

  danielj:
    name: Daniel Justus
    description: Research Lead
    avatar: img/authors/danielj.jpg

  dobrikg:
    name: Dobrik Georgiev
    description: Research Scientist
    avatar: img/authors/_default.jpg

  douglaso:
    name: Douglas Orr
    description: Research Team Lead
    avatar: img/authors/douglaso.jpg

  johannav:
    name: Johanna Vielhaben
    description: Research Scientist
    avatar: img/authors/_default.jpg

  josefd:
    name: Josef Dean
    description: Research Scientist
    avatar: img/authors/_default.jpg

  kheerann:
    name: Kheeran Naidu
    description: Research Scientist
    avatar: img/authors/_default.jpg

  lukar:
    name: Luka Ribar
    description: Research Scientist
    avatar: img/authors/lukar.jpg

  lukehg:
    name: Luke Hudlass-Galley
    description: Research Team Lead
    avatar: img/authors/lukehg.jpg

  lukep:
    name: Luke Prince
    description: Research Team Lead
    avatar: img/authors/_default.jpg

  markp:
    name: Mark Pupilli
    description: Distinguished Engineer
    avatar: img/authors/_default.jpg

  michaelp:
    name: Michael Pearce
    description: Research Scientist
    avatar: img/authors/_default.jpg

  paulb:
    name: Paul Balanca
    description: Research Team Lead
    avatar: img/authors/_default.jpg

  roberthu:
    name: Robert Hu
    description: Research Scientist
    avatar: img/authors/_default.jpg

  samho:
    name: Sam Hosegood
    description: Research Scientist
    avatar: img/authors/_default.jpg

  samot:
    name: Sam Olesker-Taylor
    description: Research Scientist
    avatar: img/authors/_default.jpg

  seanc:
    name: Seán Comerford
    description: ML Engineer
    avatar: img/authors/_default.jpg

  sylvainv:
    name: Sylvain Viguier
    description: Director, Applied AI
    avatar: img/authors/_default.jpg

  tomca:
    name: Tom Cashman
    description: Research Team Lead
    avatar: img/authors/_default.jpg

  tomp:
    name: Tom Pollak
    description: ML Engineer
    avatar: img/authors/_default.jpg

  yemanh:
    name: Yeman Brhane Hagos
    description: Research Scientist
    avatar: img/authors/_default.jpg
