authors:
  douglaso:
    name: Douglas Orr
    description: Research Scientist
    avatar: img/authors/douglaso.jpg
  lukar:
    name: Luka Ribar
    description: Research Scientist
    avatar: img/authors/lukar.jpg
