name: Public Mirror
run-name: ${{ github.actor }}: public mirror 
on:
  push:
    branches:
      - master
jobs:
  to_public:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            git@github.com:graphcore-research/graphcore-research.github.io.git
          ssh_private_key:                              # <-- use 'secrets' to pass credential information.
            ${{ secrets.BLOG_MIRROR_SSH_PRIVATE_KEY }}
