name: public-sync

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      SSH_PRIVATE_KEY: ${{ secrets.BLOG_MIRROR_SSH_PRIVATE_KEY }}
    steps:
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Checkout Private Repo
        uses: actions/checkout@v4
        with:
          repository: graphcore-research/graphcore-research.github.io-internal
          ref: main
      - name: Push to Public Repo
        run: |
          git remote add public git@github.com:graphcore-research/graphcore-research.github.io.git
          git pull
          git push public main --force
