name: public-sync

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Private Repo
        uses: actions/checkout@v4
        with:
          repository: graphcore-research/graphcore-research.github.io-internal
          ref: main
      - name: Push to Public Repo
        run: |
          git config --global user.email "charlieb@graphcore.ai"
          git config --global user.name "Charlie Blake"
          git config --global credential.helper cache
          git remote add public https://${{secrets.BLOG_MIRROR_SSH_PRIVATE_KEY}}@github.com/graphcore-research/graphcore-research.github.io.git
          git push public main
